### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by schzhu**
Adding a new paper

### CODE REVIEW

**Comment by L0Z1K** [comment]
Can you explain what is the difference between this paper and [AutoDAN: Generating Stealthy Jailbreak Prompts on Aligned Large Language Models](https://arxiv.org/pdf/2310.04451.pdf)?

**Comment by schzhu** [comment]
Sure, Seungyun! Besides the same method name, the two papers use different methods in generating the attack prompts. The one you've mentioned uses the genetic algorithm, which requires some initial manual prompts but is empirically more powerful. The one to be added uses a new gradient-based discrete optimization method that doesn't require manual input like some initial prompts, so everything is automatic, but it is relatively less effective in terms of the attack success rate than the former one.

The two papers are both submitted to ICLR, and I think they both have their merit. Please see [this tweet](https://twitter.com/sichengzhuml/status/1717194435757228410) for more information.

Thank you for your maintenance of this repo!

**Comment by schzhu** [comment]
Please let me know if you have further questions and I'm happy to answer! Thanks!

**Comment by L0Z1K** [comment]
Thanks for explanation!

**Pull request merged**
